### PR TITLE
Introduce baseline functionality

### PR DESCRIPTION
**Pull request by jacobdeery**
This is a fun little AWS Lambda app that listens for new issues (on any repo) and creates a corresponding Basecamp to-do. I made this because none of the available integrations did what we wanted them to do.

No CI yet, but I'll get that up and running next.

Feature suggestions welcome.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/aqueduct/1)

### CODE REVIEW

**Review by chrissank — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/aqueduct/1)* status: 0 of 18 files reviewed, 2 unresolved discussions (waiting on @jacobdeery, @QuantumManiac, and @wendi-yu)

___
*[src/auth.py, line 29 at r1](https://reviewable.io/reviews/waterloo-rocketry/aqueduct/1#-MRIYDly4q11fwoDDpyt:-MRIYCjZ1hZyc2f63YDr:b-38tg1v) ([raw file](https://github.com/waterloo-rocketry/aqueduct/blob/a5fa422733fe225d1b26bad1d1da8737708be37f/src/auth.py#L29)):*
> ```Python
>     ssm_client = boto3.client('ssm')
> 
>     # All tokens are stored in the AWS Systems Manager Parameter Store.
> ```

I know Lambda has environment functions built in, not sure if that'd be easier / harder than what's here, but I find it useful in Minerva.
___
*[src/basecamp/basecamp.py, line 26 at r1](https://reviewable.io/reviews/waterloo-rocketry/aqueduct/1#-MRIYmrh-Fay775gSmEh:-MRIYmrh-Fay775gSmEi:b-6qide3) ([raw file](https://github.com/waterloo-rocketry/aqueduct/blob/a5fa422733fe225d1b26bad1d1da8737708be37f/src/basecamp/basecamp.py#L26)):*
> ```Python
> 
> def extract_repos(description):
>     # Basecamp uses rich text, so the description comes wrapped in <div> tags.
> ```

What about `<b>`, `<ul>` tags? Minerva has a regex filter for removing everything and including between `<` and `>` symbols.

**Review by chrissank — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/aqueduct/1)* status: 0 of 18 files reviewed, 3 unresolved discussions (waiting on @jacobdeery, @QuantumManiac, and @wendi-yu)

*[a discussion](https://reviewable.io/reviews/waterloo-rocketry/aqueduct/1#-MRIZo5FAl6Ynvn02Z4o:-MRIZo5FAl6Ynvn02Z4p:b-x6urqc) (no related file):*
I forgot to say :lgtm:!

---

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/aqueduct/1)* status: 0 of 18 files reviewed, 3 unresolved discussions (waiting on @chrissank, @jacobdeery, @QuantumManiac, and @wendi-yu)

___
*[src/auth.py, line 29 at r1](https://reviewable.io/reviews/waterloo-rocketry/aqueduct/1#-MRIYDly4q11fwoDDpyt:-MRIZlX1EWO9zBC7BLpi:b9ngayx) ([raw file](https://github.com/waterloo-rocketry/aqueduct/blob/a5fa422733fe225d1b26bad1d1da8737708be37f/src/auth.py#L29)):*
<details><summary><i>Previously, chrissank (Chris Sankey) wrote…</i></summary><blockquote>

I know Lambda has environment functions built in, not sure if that'd be easier / harder than what's here, but I find it useful in Minerva.
</blockquote></details>

Environment variables don't work because we need to be able to modify the parameters from within the session when we refresh our tokens.
___
*[src/basecamp/basecamp.py, line 26 at r1](https://reviewable.io/reviews/waterloo-rocketry/aqueduct/1#-MRIYmrh-Fay775gSmEh:-MRI_I-A3Bj8ONB7Af0u:bt5jvzn) ([raw file](https://github.com/waterloo-rocketry/aqueduct/blob/a5fa422733fe225d1b26bad1d1da8737708be37f/src/basecamp/basecamp.py#L26)):*
<details><summary><i>Previously, chrissank (Chris Sankey) wrote…</i></summary><blockquote>

What about <b>, <ul> tags? Minerva has a regex filter for removing everything between `<` and `>`.
</blockquote></details>

The description should always look like this, so there shouldn't be any tags other than `<div>`:

**Review by QuantumManiac — APPROVED** [review]
> Reviewed 17 of 18 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/aqueduct/1)* status: all files reviewed, 3 unresolved discussions (waiting on @chrissank, @jacobdeery, and @wendi-yu)

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/aqueduct/1)* status: all files reviewed, 6 unresolved discussions (waiting on @chrissank and @jacobdeery)

*[a discussion](https://reviewable.io/reviews/waterloo-rocketry/aqueduct/1#-MRIZo5FAl6Ynvn02Z4o:-MRNFYpc1u6UM3RIGNt6:bhvs6an) (no related file):*
<details><summary><i>Previously, chrissank (Chris Sankey) wrote…</i></summary><blockquote>

I forgot to say :lgtm:!
</blockquote></details>

Yeah looks good overall, I had some comments for extensibility but as a basic implementation this looks fine. Maybe add a quick README on how to deploy and stuff at some point?

---
___
*[lambda_function.py, line 13 at r2](https://reviewable.io/reviews/waterloo-rocketry/aqueduct/1#-MRNDnSIAA2ik99GYk6m:-MRNDnSIAA2ik99GYk6n:baarct9) ([raw file](https://github.com/waterloo-rocketry/aqueduct/blob/89d91adc64d9b69804c315d074fa1b1221504b13/lambda_function.py#L13)):*
> ```Python
>     if r is None:
>         return {
>             'statusCode': 200,
> ```

Correct me if I'm wrong but the `None` handling here is essentially for repos we're not trying to track in Basecamp, right? If it is, I think we should note that in a comment and add in logically separate handling for any actual errors we encounter (like idk id not found or something), otherwise debugging sounds nightmarish in case something actually does go wrong. 
___
*[src/auth.py, line 12 at r2](https://reviewable.io/reviews/waterloo-rocketry/aqueduct/1#-MRN71-l3JyUSXv9t_ue:-MRN71-l3JyUSXv9t_uf:bfvsxlh) ([raw file](https://github.com/waterloo-rocketry/aqueduct/blob/89d91adc64d9b69804c315d074fa1b1221504b13/src/auth.py#L12)):*
> ```Python
> auth_endpoint = f'{auth_base}/new?type=web_server'
> token_endpoint = f'{auth_base}/token?type=web_server'
> refresh_endpoint = f'{auth_base}/token?type=refresh'
> ```

These are pretty simple URLs so it's probably fine but I think URLs are generally pretty fragile and it's better to use a library (like [this one](https://docs.python.org/3/library/urllib.parse.html)) to build them than to do it by hand. It's probably only relevant if we extend this though, since I doubt these URLs will change/break any time soon.
___
*[src/basecamp/basecamp.py, line 33 at r2](https://reviewable.io/reviews/waterloo-rocketry/aqueduct/1#-MRNBPpnCXNwzIghznTE:-MRNBPpnCXNwzIghznTF:b-va4i3n) ([raw file](https://github.com/waterloo-rocketry/aqueduct/blob/89d91adc64d9b69804c315d074fa1b1221504b13/src/basecamp/basecamp.py#L33)):*
> ```Python
> 
> def get_todolist(sess, project, repo_name):
>     todoset_id = extract_todoset_id(project)
> ```

Do we want handling for if this actually ends up returning `None`? Something threaded through to give a decipherable http error code?
___
*[src/basecamp/basecamp.py, line 50 at r2](https://reviewable.io/reviews/waterloo-rocketry/aqueduct/1#-MRNDDWT3DKJVxHeIUX3:-MRNDDWT3DKJVxHeIUX4:b-7pj1pq) ([raw file](https://github.com/waterloo-rocketry/aqueduct/blob/89d91adc64d9b69804c315d074fa1b1221504b13/src/basecamp/basecamp.py#L50)):*
> ```Python
>     payload = {
>         'content': event['title'],
>         'description': f'<div>{event["desc"]}</div><div>{event["url"]}</div>'
> ```

lol the hard coding makes me itch but I don't think there's really an html handler for Python :^)

**Pull request merged**
